;***************************************************************************
;
;	    Filename: PluckSlave.ASM
;	    Date: 11/06/2024
;	    File Version: 1
;	    Author: Owen Fujii
;	    Company: Idaho State University
;	    Description: A Program for a slave I2C device that plucks the strings
;			    of a bass guitar
;**************************************************************************
	
;*************************************************************************
; 
;	    Revision History:
;   
;	    Modified as listed
;	    Started 11/06/2024
;
;*************************************************************************
    
    ; PIC16F1788 Configuration Bit Settings

; Assembly source line config statements

	#include "p16f1789.inc"
	#INCLUDE <PluckSetup.inc>
	#INCLUDE <PluckPOPout.inc>
	#INCLUDE <PluckPUSHin.inc>

; CONFIG1
; __config 0xE9A4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_ON
; CONFIG2
; __config 0xDFFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_OFF

 
 ;*********************
 ;Define Constants
 ;*********************
 
 ;***********************************************************
 ; GENERAL PURPOSE REGISTER ALLOCATIONS
 ; RESERVED H'20' AND H'21' FOR STATUS SAVE
	BUFFER	    EQU H'022'
	VBYTE	    EQU H'023'
	SBYTE	    EQU H'024'
	TEMP	    EQU H'025'
	ALTSTORE    EQU H'026'
	ALTCLEAR    EQU H'027'

 

    ORG H'000'					
    GOTO SETUP					;RESET CONDITION GOTO SETUP
    ORG H'004'
    GOTO INTER
    
    
    
SETUP
    BANKSEL OSCCON
    MOVLW H'072'	    ; SET 8MHZ INTERNAL OSSCILATOR
    MOVWF OSCCON
    BANKSEL OSCSTAT
    BTFSC OSCSTAT,OSTS	    ; WAIT FOR OSSCILATOR TO BE READY
    GOTO $-1
    CALL START		    ; CALL SETUP INCLUDE
    ; I2C SLAVE SETUP
    BANKSEL SSP1CON1
    MOVLW H'036'	    ; SET 7 BIT SLAVE I2C
    MOVWF SSP1CON1
    BANKSEL SSP1ADD
    MOVLW H'020'	    ; SET SLAVE ADDRESS A 0X10
    MOVWF SSP1ADD
    BANKSEL SSP1CON2
    BSF SSP1CON2,SEN	    ; ENABLE CLOCK STRETCH
    BANKSEL SSP1CON3
    CLRF SSP1CON3
    BSF SSP1CON3,AHEN	    ; ENABLE CLOCK STRETCH FOR ADDRESS AND DATA
    BSF SSP1CON3,DHEN
    ; SET PIN FUNCTIONS
    BANKSEL APFCON1
    CLRF APFCON1	    ; SET PORTS
    BANKSEL APFCON2
    CLRF APFCON2	    ; SET PORTS
    ; ENABLE I2C INTERRUPTS
    BANKSEL PIE1
    BSF PIE1,SSP1IE
    ; CONFIGURE GPRS
    BANKSEL INTCON
    CLRF BUFFER
    MOVLW H'055'
    MOVWF ALTSTORE	    ; SET THE FIRST BITS FOR EACH ALTERNATING
    CLRF ALTCLEAR	    ; PLUCKING SET
    ; ENABLE INTERRUPTS
    BSF INTCON,GIE	    ; ENABLE INTERRUPTS
    BSF INTCON,PEIE
    GOTO MAIN

MAIN
    NOP
    BANKSEL SSP1STAT
    BTFSC SSP1STAT,1
    CALL STOP
    BANKSEL PORTB
    BTFSS BUFFER,2
    GOTO MAIN
    BTFSC SBYTE,7
    GOTO PICK
    BTFSC SBYTE,3
    GOTO PLUCKE
    BTFSC SBYTE,2
    GOTO PLUCKA
    BTFSC SBYTE,1
    GOTO PLUCKD
    BTFSC SBYTE,0
    GOTO PLUCKG
    GOTO MAIN
    
PLUCKE
    BTFSS ALTSTORE,0	; USE PLUCK UNIT 0 IF SET
    GOTO $+5
    BSF PORTB,0
    BSF ALTSTORE,1	; SET BIT TO USE UNIT 1 NEXT ITERATION
    BCF ALTSTORE,0
    BSF ALTCLEAR,0	; SET THAT 
    BTFSS ALTSTORE,1
    GOTO $+5
    BSF PORTB,1
    BSF ALTSTORE,0
    BCF ALTSTORE,1
    BSF ALTCLEAR,1
    CALL STARTTMR
    GOTO MAIN
    
    
    
PLUCKA
    
PLUCKD
    
PLUCKG

PICK
    
STARTTMR
    BANKSEL TMR1H
    MOVLW H'09E'
    MOVWF TMR1H
    BANKSEL TMR1L
    MOVLW H'057'
    MOVWF TMR1L	    ; LOAD TMR REGISTERS TO PRODUCE A 25K COUNT
    BANKSEL T1CON
    MOVLW H'034'    
    MOVWF T1CON
    BSF T1CON,0	    ; ENABLE TIMER 1
    BANKSEL PIE1
    BSF PIE1,TMR1IE
    RETURN
    
    
STOP
    BANKSEL SSP1CON1
    BCF SSP1CON1,SSPEN
    NOP
    NOP
    BSF SSP1CON1,SSPEN
    RETURN
    
INTER
    BANKSEL INTCON
    CLRF INTCON
    CALL PUSHIN
    BCF PORTB,2
    BANKSEL PIR1
    BTFSC PIR1,SSP1IF	    ; CHECK MSSP INTERRUPT FLAG
    CALL RECIEVE	
    BANKSEL INTCON
    BSF INTCON,GIE
    BSF INTCON,PEIE
    CALL POPOUT
    RETFIE
    
RECIEVE
    BANKSEL PIR1
    CLRF PIR1		; CLEAR FLAG
    BCF PORTB,2
    BANKSEL SSP1BUF 
    MOVF SSP1BUF,0	; READ RECIEVED DATA
    BANKSEL PORTB
    MOVWF TEMP
    BTFSC BUFFER,1
    GOTO STRINGSEL
    BTFSC BUFFER,0	; CHECK IF THIS IS DATA OR ADDRESS
    GOTO VELOCITY
    BSF BUFFER,0	; SET ADDRESS RECIEVE
    BANKSEL SSP1CON1	
    BSF SSP1CON1,CKP	; RELEASE CLOCK LINE
    RETURN
    
VELOCITY
    MOVFW TEMP
    MOVWF VBYTE
    BSF BUFFER,1	; SET VELOCITY BYTE RECIEVE FLAG
    BANKSEL SSP1CON1	
    BSF SSP1CON1,CKP	; RELEASE CLOCK LINE
    RETURN
    
STRINGSEL
    MOVFW TEMP
    MOVWF SBYTE
    BSF BUFFER,2	; SET STRING RECIEVE FLAG
    BANKSEL SSP1CON1	
    BSF SSP1CON1,CKP	; RELEASE CLOCK LINE
    RETURN

END





